print('Для работы с файлами в Python есть встроенные функции open, write, close')
print("При создании или редактировании файла нужно указывать операторов уточнения 'w'- создание файла, если он не существовал ранее, 'w+' создание или перезапись файла, 'a+' - дополнение файла")
textfile = open ("TextFile.txt", 'w+', encoding='utf-8')
textfile.write('Кроваво-черное ничто пустилось вить систему клеток, связанных внутри, клеток, связанных внутри, клеток в едином стебле и явственно, до жути на фоне тьмы ввысь белым бил фонтан')
print ("Для сохранения файла требуется его закрыть")
textfile.close()
print("Для дополнения текста используется уточнение 'a+', для сноски на новую строку неужно указывать \n")
textfile = open ("TextFile.txt", 'a+', encoding='utf-8')
textfile.write('\nВот силлогизм: другие люди умирают, но я Не другой; поэтому я не умру.')
textfile.close()
print("При указании неверного адреса файла или его наименования Python выдаст ошибку")
print("Для уточнения адреса требуется указать команду pwd")
print("Чтобы вытащить данные из файла в python, требуется указать textfile.read()")
textfile = open ("TextFile.txt", encoding='utf-8')
textfile.seek(0)  # Перемещаем указатель в начало файла
print(textfile.read())
textfile.close()
print("В дальнейшем данные можно сохранить в отдельную переменную для использования в программе:")
textfile = open ("TextFile.txt", encoding='utf-8')
contents = textfile.read()
textfile.seek(0)
print("Или преобразовать в список:")
contentslines = textfile.readlines()
print(contentslines)
textfile.close()